# Solving the Shortest Paths Problem by using matrices

In [2]:
import numpy as np

## 1 Define the direct distance matrix of all pairs of nodes
Label all nodes $A, B ,C, D, E, F, G$ by using counting numbers $0,1,2,3,4,5,6,$, and we have node $i$, where $i \in \{ i \in \mathcal{Z} | 0 \leq i \leq 6  \} $.

Assume that $O=(a_{i,j})_{7 \times 7}$ is the matrix represeting the direct distances between two directly reachable node $i$ and node $j$, where 
$$a_{i,j} = 
\begin{cases}
0 & if \ i=j \\
d(i,j) & if \ node \ i \ and \ node \ j \ can \ be \ directly \ reached \\
\infty & if \ \ node \ i \ and \ node \ j \ can \ not \ be \ directly \ reached
\end{cases}
$$
Without loss of generality, we can call $O$ the **directe distance matrix**. This matrix can be easily generalised to the case where we have $n$ nodes and we will have the matrix $O_{n \times n}$.

### Remark
In our case, the order of node $i$ and node $j$ matters, since the equation $d(i,j)=d(j,i)$ may not hold.

In [10]:
# Input the direct distance matrix
O = np.array([[0,1,5,3, np.inf, np.inf, np.inf], [np.inf, 0, np.inf, 9, 6, np.inf, np.inf], [np.inf, np.inf, 0, np.inf, np.inf, 2, np.inf], [np.inf, np.inf, np.inf, 0, np.inf, 4, 8], [np.inf, np.inf, np.inf, np.inf, 0, np.inf, 4], [np.inf, np.inf, np.inf, np.inf, np.inf, 0, 1], [np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, 0]])
print(O)

[[ 0.  1.  5.  3. inf inf inf]
 [inf  0. inf  9.  6. inf inf]
 [inf inf  0. inf inf  2. inf]
 [inf inf inf  0. inf  4.  8.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


## 2 Bellman equation v.s. Min-plus matrix multiplication
Let's define a new matrix-multiplication-like operation between two matrices, i.e., the so-called Min-plus matrix multiplication.
### Def. (Min-plus matrix multiplication)
Given two $n\times n$ matrices $A=(a_{i,j})$  and  $B=(b_{i,j})$, their distance product $C=(c_{i,j}) = A \oplus B $ is defined as an $n \times n$ matrix such that 
$$c_{i,j}= \min_{k \in \{1,2,...,n \} } \{ a_{i,k} + b_{k,j} \}  $$ 
which can be eactly functioned as the operation of the main loop part of the Bellman equation for the Shortest Path Problem.

In [11]:
# Define the Min-Plus Matrix Multiplication between two n*n matrices

def min_plus_product(A, B):
    B = np.transpose(B)
    Y = np.zeros((len(B), len(A)))
    for i in range(len(B)):
        Y[i] = (A+B[i]).min(1)
    return np.transpose(Y)

## 3 Find the shortest distance between two nodes
Therefore, the power $k$ of the direct distance matrix $O$, denoted by $O^k$, gives the distances between nodes using at most $k$ paths.

### Proposition
Consider $O^k = (o^k_{i,j}) = O^{k-1} \oplus O $, where $k \in \{ k \in \mathcal{Z} | k \geq 1 \}$ and $O^0=(o^0_{i,j})$ is a matrix all of whose entities are 0s, i.e., $o^0_{i,j}=0$ for all $i,j$. If we have 
$$o^{k-1}_{i,j} \neq o^{k}_{i,j} $$ and $$o^{k}_{i,j} = o^{k+1}_{i,j}$$,
then we can say that it takes at most k paths from node $i$ to node $j$, with the shortest distance $o^k_{i,j}$.

### Method 1
If the dimension of the direct distance matrix is small, then we can solve the problem by checking $O^k$ one by one from $k =1$.

In [5]:
O2 = min_plus_product(O,O)
print(O2)

[[ 0.  1.  5.  3.  7.  7. 11.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In [6]:
O3 = min_plus_product(O2,O)
print(O3)

[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In [7]:
O4 = min_plus_product(O3,O)
print(O4)

[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In [8]:
O5 = min_plus_product(O4,O)
print(O5)

[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In our example, we want to find the least-cost paths between node A and node G, i.e., node 0 and node 6.

Since we have $o^2_{0,6} \neq o^3_{0,6}$ and $o^3_{0,6} = o^4_{0,6}$, by Proposition, then
the least-cost paths between these two nodes are 3, and its shortest distance should be $o^3_{1,7}=8$.

### Method 2
Alternatively, we can use a loop to help us find the least-cost paths from node 0 to node 6, i.e., from node A to node G, according to the **Proposition**.


In [9]:
O_old = O
O_new = min_plus_product(O_old, O)
o_old = O_old[0, 6]
o_new = O_new[0, 6]
d = o_new - o_old
i = 1
while d != 0:
    o_old = O_new[0, 6]
    O_old = O_new
    O_new = min_plus_product(O_old, O)
    o_new = O_new[0, 6]
    d = o_new - o_old
    i += 1

print(i)
print(o_new)
print(O_new)

3
8.0
[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


### Method 3
And alternatively again, we can define a function and include the loop in the function so that we can find the least-cost paths and its shortest distance between any two potentially reachable nodes $x$ and node $y$.

In [15]:
def compute_path(O, x, y):
    """
    O is the direct distance matrix
    x is the node we are going to start from
    y is the node we are going to reach finally.
    """
    O_old = O
    O_new = min_plus_product(O_old, O)
    o_old = O_old[x, y]
    o_new = O_new[x, y]
    d = o_new - o_old
    i = 1
    while d != 0:
        o_old = O_new[x, y]
        O_old = O_new
        O_new = min_plus_product(O_old, O)
        o_new = O_new[x, y]
        d = o_new - o_old
        i = i + 1
    return (i, o_new, O_new)

Therefore, we can easily find the shortest paths and the least cost from node 0 to node 6.

In [16]:
compute_path(O, 0, 6)

(3, 8.0, array([[ 0.,  1.,  5.,  3.,  7.,  7.,  8.],
        [inf,  0., inf,  9.,  6., 13., 10.],
        [inf, inf,  0., inf, inf,  2.,  3.],
        [inf, inf, inf,  0., inf,  4.,  5.],
        [inf, inf, inf, inf,  0., inf,  4.],
        [inf, inf, inf, inf, inf,  0.,  1.],
        [inf, inf, inf, inf, inf, inf,  0.]]))

## Reference


1. Uri Zwick (2002): "All pairs shortest paths using bridging sets and rectangular matrix multiplication,". Journal of the ACM, 49, 289–317.
2. Liam Roditty and Asaf Shapira (2011):"All-Pairs Shortest Paths with a Sublinear Additive Error," Journal of ACM (TALG),Vol.7,Issue 4, 45.