# 1 Shortest paths problem

## 1.1 Overview

## 1.2 Outline of the problem

The shortest path problem is one of finding how to traverse a graph from one specified node to another at minimum cost.

We wish to travel from node 1 to node n at minimum cost

1. Arrows indicate the movements we can take.
2. Numbers on edges indicate the cost of traveling that edge.

Possible interpretations of the graph include

1. Minimum cost for supplier to reach a destination.
2. Routing of packets on the internet (minimize time)

## 1.3 Finding least-cost paths

For small graphs, it is easy to go through all cases, but for large graphs, we need a systematic solution.

Let $\mathcal{J(v)}$ denote the minimum cost-to-go from node $v$, understood as the total cost from $v$ if we take the best route.

Suppose that we know $J(v)$ for each node $v$.

The best path can be found as follows:

1. Start at A

2. From node $v$, move to any node that solves
   $$
   \min_{w \in F_v}\{ c(v,w)+J(w) \}
   $$

where

1. $F_v$ is the set of nodes that can be reached from $v$ in one step.
2. $c(v,w)$ is the cost of traveling from $v$ to $w$.

Hence, if we know the function $J$, then finding the best path is almost trivial.

But how to find $J$?

Some thought will convince you that, for every node $v$, the function $J$ satisfies
$$
J(v)= \min_{w \in F_v}\{ c(v,w)+J(w) \}
$$
This is known as the Bellman equation (Richard Bellman)

## 1.4 Solving for minimum cost-to-go

The standard algorithm for finding $J$ is to start with 
$$
J_0(v)=M \ if \ v \neq destination, else \ J_0(v)=0
$$
where $M$ can actually be any real number here.

Now we use the following algorithm

1. Set $n=0$
2. Set $J_{n+1} (v)= \min_{w \in F_v} \{ c(v,w)+J_n(w) \}$ for all $v$
3. If $J_{n+1}$ and $J_n$ are not equal then increment $n$, go to 2

In general, this sequence converges to $J$.

## Exercise 1

In [1]:
%%file graph.txt
node0, node1 0.04, node8 11.11, node14 72.21
node1, node46 1247.25, node6 20.59, node13 64.94
node2, node66 54.18, node31 166.80, node45 1561.45
node3, node20 133.65, node6 2.06, node11 42.43
node4, node75 3706.67, node5 0.73, node7 1.02
node5, node45 1382.97, node7 3.33, node11 34.54
node6, node31 63.17, node9 0.72, node10 13.10
node7, node50 478.14, node9 3.15, node10 5.85
node8, node69 577.91, node11 7.45, node12 3.18
node9, node70 2454.28, node13 4.42, node20 16.53
node10, node89 5352.79, node12 1.87, node16 25.16
node11, node94 4961.32, node18 37.55, node20 65.08
node12, node84 3914.62, node24 34.32, node28 170.04
node13, node60 2135.95, node38 236.33, node40 475.33
node14, node67 1878.96, node16 2.70, node24 38.65
node15, node91 3597.11, node17 1.01, node18 2.57
node16, node36 392.92, node19 3.49, node38 278.71
node17, node76 783.29, node22 24.78, node23 26.45
node18, node91 3363.17, node23 16.23, node28 55.84
node19, node26 20.09, node20 0.24, node28 70.54
node20, node98 3523.33, node24 9.81, node33 145.80
node21, node56 626.04, node28 36.65, node31 27.06
node22, node72 1447.22, node39 136.32, node40 124.22
node23, node52 336.73, node26 2.66, node33 22.37
node24, node66 875.19, node26 1.80, node28 14.25
node25, node70 1343.63, node32 36.58, node35 45.55
node26, node47 135.78, node27 0.01, node42 122.00
node27, node65 480.55, node35 48.10, node43 246.24
node28, node82 2538.18, node34 21.79, node36 15.52
node29, node64 635.52, node32 4.22, node33 12.61
node30, node98 2616.03, node33 5.61, node35 13.95
node31, node98 3350.98, node36 20.44, node44 125.88
node32, node97 2613.92, node34 3.33, node35 1.46
node33, node81 1854.73, node41 3.23, node47 111.54
node34, node73 1075.38, node42 51.52, node48 129.45
node35, node52 17.57, node41 2.09, node50 78.81
node36, node71 1171.60, node54 101.08, node57 260.46
node37, node75 269.97, node38 0.36, node46 80.49
node38, node93 2767.85, node40 1.79, node42 8.78
node39, node50 39.88, node40 0.95, node41 1.34
node40, node75 548.68, node47 28.57, node54 53.46
node41, node53 18.23, node46 0.28, node54 162.24
node42, node59 141.86, node47 10.08, node72 437.49
node43, node98 2984.83, node54 95.06, node60 116.23
node44, node91 807.39, node46 1.56, node47 2.14
node45, node58 79.93, node47 3.68, node49 15.51
node46, node52 22.68, node57 27.50, node67 65.48
node47, node50 2.82, node56 49.31, node61 172.64
node48, node99 2564.12, node59 34.52, node60 66.44
node49, node78 53.79, node50 0.51, node56 10.89
node50, node85 251.76, node53 1.38, node55 20.10
node51, node98 2110.67, node59 23.67, node60 73.79
node52, node94 1471.80, node64 102.41, node66 123.03
node53, node72 22.85, node56 4.33, node67 88.35
node54, node88 967.59, node59 24.30, node73 238.61
node55, node84 86.09, node57 2.13, node64 60.80
node56, node76 197.03, node57 0.02, node61 11.06
node57, node86 701.09, node58 0.46, node60 7.01
node58, node83 556.70, node64 29.85, node65 34.32
node59, node90 820.66, node60 0.72, node71 0.67
node60, node76 48.03, node65 4.76, node67 1.63
node61, node98 1057.59, node63 0.95, node64 4.88
node62, node91 132.23, node64 2.94, node76 38.43
node63, node66 4.43, node72 70.08, node75 56.34
node64, node80 47.73, node65 0.30, node76 11.98
node65, node94 594.93, node66 0.64, node73 33.23
node66, node98 395.63, node68 2.66, node73 37.53
node67, node82 153.53, node68 0.09, node70 0.98
node68, node94 232.10, node70 3.35, node71 1.66
node69, node99 247.80, node70 0.06, node73 8.99
node70, node76 27.18, node72 1.50, node73 8.37
node71, node89 104.50, node74 8.86, node91 284.64
node72, node76 15.32, node84 102.77, node92 133.06
node73, node83 52.22, node76 1.40, node90 243.00
node74, node81 1.07, node76 0.52, node78 8.08
node75, node92 68.53, node76 0.81, node77 1.19
node76, node85 13.18, node77 0.45, node78 2.36
node77, node80 8.94, node78 0.98, node86 64.32
node78, node98 355.90, node81 2.59
node79, node81 0.09, node85 1.45, node91 22.35
node80, node92 121.87, node88 28.78, node98 264.34
node81, node94 99.78, node89 39.52, node92 99.89
node82, node91 47.44, node88 28.05, node93 11.99
node83, node94 114.95, node86 8.75, node88 5.78
node84, node89 19.14, node94 30.41, node98 121.05
node85, node97 94.51, node87 2.66, node89 4.90
node86, node97 85.09
node87, node88 0.21, node91 11.14, node92 21.23
node88, node93 1.31, node91 6.83, node98 6.12
node89, node97 36.97, node99 82.12
node90, node96 23.53, node94 10.47, node99 50.99
node91, node97 22.17
node92, node96 10.83, node97 11.24, node99 34.68
node93, node94 0.19, node97 6.71, node99 32.77
node94, node98 5.91, node96 2.03
node95, node98 6.17, node99 0.27
node96, node98 3.32, node97 0.43, node99 5.87
node97, node98 0.30
node98, node99 0.33
node99,

Writing graph.txt


In [2]:
def read_graph(in_file):
    graph = {}
    infile = open(in_file)
    for line in infile:
        elements = line.split(',')
        node = elements.pop(0)
        graph[node] = []
        if node != 'node99':
            for element in elements:
                destination, cost = element.split()
                graph[node].append((destination, float(cost)))
    infile.close()
    return graph

In [6]:
def update_J(J, graph):
    next_J = {}
    for node in graph:
        if node == 'node99':
            next_J[node] = 0
        else:
            next_J[node] = min(cost + J[dest] for dest, cost in graph[node])
    return next_J


In [10]:
def print_best_path(J, graph):
    sum_costs = 0
    current_location = 'node0'
    while current_location != 'node99':
        print(current_location)
        running_min = 1e100
        for destination, cost in graph[current_location]:
            cost_of_path = cost + J[destination]
            if cost_of_path < running_min:
                running_min = cost_of_path
                minimizer_cost = cost
                minimizer_dest = destination
        current_location = minimizer_dest
        sum_costs += minimizer_cost
    print('node99\n')                    # ? \n
    print('Cost: ', sum_costs)

In [11]:
graph = read_graph('graph.txt')
M = 1e10
J = {}
for node in graph:
    J[node] = M

J['node99'] = 0

while True:
    next_J = update_J(J, graph)
    if next_J == J:
        break
    else:
        J = next_J

In [12]:
print_best_path(J, graph)

node0
node8
node11
node18
node23
node33
node41
node53
node56
node57
node60
node67
node70
node73
node76
node85
node87
node88
node93
node94
node96
node97
node98
node99

Cost:  160.55000000000007


## Exercise 2 Solving the Shortest Paths Problem by using matrices

In [13]:
import numpy as np

### 1 Define the direct distance matrix of all pairs of nodes
Label all nodes $A, B ,C, D, E, F, G$ by using counting numbers $0,1,2,3,4,5,6,$, and we have node $i$, where $i \in \{ i \in \mathcal{Z} | 0 \leq i \leq 6  \} $.

Assume that $O=(a_{i,j})_{7 \times 7}$ is the matrix represeting the direct distances between two directly reachable node $i$ and node $j$, where 
$$a_{i,j} = 
\begin{cases}
0 & if \ i=j \\
d(i,j) & if \ node \ i \ and \ node \ j \ can \ be \ directly \ reached \\
\infty & if \ \ node \ i \ and \ node \ j \ can \ not \ be \ directly \ reached
\end{cases}
$$
Without loss of generality, we can call $O$ the **directe distance matrix**. This matrix can be easily generalised to the case where we have $n$ nodes and we will have the matrix $O_{n \times n}$.

#### Remark
In our case, the order of node $i$ and node $j$ matters, since the equation $d(i,j)=d(j,i)$ may not hold.

In [14]:
# Input the direct distance matrix
O = np.array([[0,1,5,3, np.inf, np.inf, np.inf], [np.inf, 0, np.inf, 9, 6, np.inf, np.inf], [np.inf, np.inf, 0, np.inf, np.inf, 2, np.inf], [np.inf, np.inf, np.inf, 0, np.inf, 4, 8], [np.inf, np.inf, np.inf, np.inf, 0, np.inf, 4], [np.inf, np.inf, np.inf, np.inf, np.inf, 0, 1], [np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, 0]])
print(O)

[[ 0.  1.  5.  3. inf inf inf]
 [inf  0. inf  9.  6. inf inf]
 [inf inf  0. inf inf  2. inf]
 [inf inf inf  0. inf  4.  8.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


### 2 Bellman equation v.s. Min-plus matrix multiplication
Let's define a new matrix-multiplication-like operation between two matrices, i.e., the so-called Min-plus matrix multiplication.
### Def. (Min-plus matrix multiplication)
Given two $n\times n$ matrices $A=(a_{i,j})$  and  $B=(b_{i,j})$, their distance product $C=(c_{i,j}) = A \oplus B $ is defined as an $n \times n$ matrix such that 
$$c_{i,j}= \min_{k \in \{1,2,...,n \} } \{ a_{i,k} + b_{k,j} \}  $$ 
which can be eactly functioned as the operation of the main loop part of the Bellman equation for the Shortest Path Problem.

In [15]:
# Define the Min-Plus Matrix Multiplication between two n*n matrices

def min_plus_product(A, B):
    B = np.transpose(B)
    Y = np.zeros((len(B), len(A)))
    for i in range(len(B)):
        Y[i] = (A+B[i]).min(1)
    return np.transpose(Y)

### 3 Find the shortest distance between two nodes
Therefore, the power $k$ of the direct distance matrix $O$, denoted by $O^k$, gives the distances between nodes using at most $k$ paths.

#### Proposition
Consider $O^k = (o^k_{i,j}) = O^{k-1} \oplus O $, where $k \in \{ k \in \mathcal{Z} | k \geq 1 \}$ and $O^0=(o^0_{i,j})$ is a matrix all of whose entities are 0s, i.e., $o^0_{i,j}=0$ for all $i,j$. If we have 
$$o^{k-1}_{i,j} \neq o^{k}_{i,j} $$ and $$o^{k}_{i,j} = o^{k+1}_{i,j}$$,
then we can say that it takes at most k paths from node $i$ to node $j$, with the shortest distance $o^k_{i,j}$.

#### Method 1
If the dimension of the direct distance matrix is small, then we can solve the problem by checking $O^k$ one by one from $k =1$.

In [16]:
O2 = min_plus_product(O,O)
print(O2)

[[ 0.  1.  5.  3.  7.  7. 11.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In [17]:
O3 = min_plus_product(O2,O)
print(O3)

[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In [18]:
O4 = min_plus_product(O3,O)
print(O4)

[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In [19]:
O5 = min_plus_product(O4,O)
print(O5)

[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


In our example, we want to find the least-cost paths between node A and node G, i.e., node 0 and node 6.

Since we have $o^2_{0,6} \neq o^3_{0,6}$ and $o^3_{0,6} = o^4_{0,6}$, by Proposition, then
the least-cost paths between these two nodes are 3, and its shortest distance should be $o^3_{1,7}=8$.

#### Method 2
Alternatively, we can use a loop to help us find the least-cost paths from node 0 to node 6, i.e., from node A to node G, according to the **Proposition**.



In [20]:
O_old = O
O_new = min_plus_product(O_old, O)
o_old = O_old[0, 6]
o_new = O_new[0, 6]
d = o_new - o_old
i = 1
while d != 0:
    o_old = O_new[0, 6]
    O_old = O_new
    O_new = min_plus_product(O_old, O)
    o_new = O_new[0, 6]
    d = o_new - o_old
    i += 1

print(i)
print(o_new)
print(O_new)

3
8.0
[[ 0.  1.  5.  3.  7.  7.  8.]
 [inf  0. inf  9.  6. 13. 10.]
 [inf inf  0. inf inf  2.  3.]
 [inf inf inf  0. inf  4.  5.]
 [inf inf inf inf  0. inf  4.]
 [inf inf inf inf inf  0.  1.]
 [inf inf inf inf inf inf  0.]]


### Method 3
And alternatively again, we can define a function and include the loop in the function so that we can find the least-cost paths and its shortest distance between any two potentially reachable nodes $x$ and node $y$.

In [23]:
def compute_path(O, x, y):
    """
    O is the direct distance matrix
    x is the node we are going to start from
    y is the node we are going to reach finally.
    """
    O_old = O
    O_new = min_plus_product(O_old, O)
    o_old = O_old[x, y]
    o_new = O_new[x, y]
    d = o_new - o_old
    i = 1
    while d != 0:
        o_old = O_new[x, y]
        O_old = O_new
        O_new = min_plus_product(O_old, O)
        o_new = O_new[x, y]
        d = o_new - o_old
        i = i + 1
    return (i, o_new, O_new)

Therefore, we can easily find the shortest paths and the least cost from node 0 to node 6.

In [24]:
compute_path(O, 0, 6)

(3, 8.0, array([[ 0.,  1.,  5.,  3.,  7.,  7.,  8.],
        [inf,  0., inf,  9.,  6., 13., 10.],
        [inf, inf,  0., inf, inf,  2.,  3.],
        [inf, inf, inf,  0., inf,  4.,  5.],
        [inf, inf, inf, inf,  0., inf,  4.],
        [inf, inf, inf, inf, inf,  0.,  1.],
        [inf, inf, inf, inf, inf, inf,  0.]]))